### ISSUE TITLE
when babs-init fails, it should clean up

### ISSUE THREAD

**Issue by asmacdo** [PennLINC/babs#25]
if babs-init is run and does not complete, it leaves an invalid setup on the filesystem. IMO if babs-init does not finish, it should clean up the files it created. Alternatively, if babs-init is idempotent, it could just be used until the setup is correct.

**Comment by zhao-cy** [comment]
Hi Austin! 

Thanks for the suggestion! My plan was to enhance `babs-init` so that it can be rerun to finish the process. For example if the first round of `babs-init` has error with some invalid inputs from the user, user would fix it and rerun `babs-init` to finish the setup process. In addition, `babs-check-setup` (which is ongoing now, not fully ready for users) will make sure the setup by `babs-init` are valid and completed.

Right now in theory user could rerun `babs-init` if they fix the invalid input (if there is) - it should finish the process. However, currently it's just not robust enough to detect which step to re-do but I will enhance this. So for now, it probably needs user to delete the BABS project folder it generated and rerun `babs-init`.

Let me know if this makes sense to you and if you have any suggestions/comments on the plan?

Thanks,
Chenying

**Comment by zhao-cy** [comment]
Hi Austin!

I talked to Matt and I realized that it was not a good idea to repeating `babs-init` upon existing BABS project folders - it will be scary if anyone accidentally reruns `babs-init` on a BABS project with successfully finished jobs. I now agree with you - when it fails, it's better to ask `babs-init` to clean up the failed BABS project folder at the end. In my current implementation (in pull request #19 - not ready to merge into main yet), I'm following this strategy. In addition, I also added a new argument`--keep-if-failed` in this PR so that we developers can ask it to leave failed BABS as it is, for debugging purpose if needed.

Thanks!
Chenying
